apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: prime-numbers-caller-sequential
  namespace: openfaas-fn
spec:
  image: itspeetah/np-prime-numbers-caller:latest
  labels:
    com.openfaas.scale.factor: "20"
    com.openfaas.scale.max: "100"
    com.openfaas.scale.min: "1"
    com.openfaas.scale.zero: "false"
    edgeautoscaler.polimi.it/scheduler: edge-autoscaler
  name: prime-numbers-caller-sequential
  readOnlyRootFilesystem: false
  limits:
    cpu: "200m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: prime-numbers-caller-sequential
  labels:
    name: prime-numbers-caller-sequential
  namespace: openfaas-fn
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    edgeautoscaler.polimi.it/function-name: "prime-numbers-caller-sequential"
    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
---
apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: prime-numbers-caller-sequential
  namespace: openfaas-fn
spec:
  metric:
    responseTime: 100m
  defaultResources:
    cpu: "300m"
    memory: "768Mi"
  minResources:
    memory: 10Mi
    cpu: 300m
  maxResources:
    memory: 2048Mi
    cpu: 20000m
  recommenderLogic: dependencyAware
  service:
    container: prime-numbers-caller-sequential
    selector:
      matchLabels:
        name: prime-numbers-caller-sequential
---
apiVersion: neptuneplus.polimi.it/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: cepdag-controller
    app.kubernetes.io/managed-by: kustomize
  name: depdag-prime-numbers-caller-sequential
  namespace: openfaas-fn # Specify the namespace where you want to create this resource
spec:
  nodes:
    - functionName: prime-numbers-caller-sequential
      functionNamespace: openfaas-fn
      nominalResponseTime: 100m
      invocations:
        - functionName: prime-numbers-invoked-sequential
          functionNamespace: openfaas-fn
          edgeId: 1
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-sequential
          functionNamespace: openfaas-fn
          edgeId: 2
          edgeMultiplier: 1
        # - functionName: prime-numbers-invoked-sequential
        #   functionNamespace: openfaas-fn
        #   edgeId: 3
        #   edgeMultiplier: 1
        # - functionName: prime-numbers-invoked-sequential
        #   functionNamespace: openfaas-fn
        #   edgeId: 4
        #   edgeMultiplier: 1
        # - functionName: prime-numbers-invoked-sequential
        #   functionNamespace: openfaas-fn
        #   edgeId: 5
        #   edgeMultiplier: 1
    - functionName: prime-numbers-invoked-sequential
      functionNamespace: openfaas-fn
      nominalResponseTime: 100m
      invocations: []

---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: prime-numbers-invoked-sequential
  namespace: openfaas-fn
spec:
  image: itspeetah/np-prime-numbers-go:latest
  labels:
    com.openfaas.scale.factor: "20"
    com.openfaas.scale.max: "100"
    com.openfaas.scale.min: "1"
    com.openfaas.scale.zero: "false"
    edgeautoscaler.polimi.it/scheduler: edge-autoscaler
  name: prime-numbers-invoked-sequential
  readOnlyRootFilesystem: false
  limits:
    cpu: "200m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: prime-numbers-invoked-sequential
  labels:
    name: prime-numbers-invoked-sequential
  namespace: openfaas-fn
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    edgeautoscaler.polimi.it/function-name: "prime-numbers-invoked-sequential"
    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
---
apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: prime-numbers-invoked-sequential
  namespace: openfaas-fn
spec:
  metric:
    responseTime: 100m
  defaultResources:
    cpu: "300m"
    memory: "768Mi"
  minResources:
    memory: 10Mi
    cpu: 300m
  maxResources:
    memory: 2048Mi
    cpu: 20000m
  recommenderLogic: dependencyAware
  service:
    container: prime-numbers-invoked-sequential
    selector:
      matchLabels:
        name: prime-numbers-invoked-sequential
