# Stage 1: Build the Go binaries
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod .

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/bin/program ./cmd

FROM alpine:latest AS function
EXPOSE 8080
WORKDIR /app

ENV PRIME_NUMBERS_URL_PARALLEL="http://prime-numbers-invoked-parallel.default.svc.cluster.local/prime/20000"
ENV PRIME_NUMBERS_URL_SEQUENTIAL="http://prime-numbers-invoked-sequential.default.svc.cluster.local/prime/20000"
ENV SERVICE_PORT="8080"

COPY --from=builder /app/bin/program .
ENTRYPOINT ["./program"]